// Writes hub/timings.js from the latest automated runs, so the hub's "Observed timing" stays current:
// the full play-through in playtest-output/results.json (desktop keyboard) and the phone walk-throughs
// from tools/walkthrough.mjs (--walks=dir1,dir2: each dir's walk.json; the mud and the firm way).
//
// Usage: node tools/hub-timings.mjs [--walks=playtest-output/walk-final,playtest-output/walk-firm]
import fs from 'node:fs';
import path from 'node:path';

const ROOT = path.resolve(import.meta.dirname, '..');
const walks = (process.argv.find((a) => a.startsWith('--walks=')) || '--walks=playtest-output/walk-final,playtest-output/walk-firm').slice(8).split(',');
const ORDER = ['search', 'prints', 'call2', 'creak', 'locked', 'over', 'park', 'lane', 'bunny', 'urgency', 'fork', 'reveal', 'argument', 'stay', 'end'];
const SHORT = { search: 'start', prints: 'prints', call2: 'call', creak: 'creak', locked: 'locked', over: 'over', park: 'park', lane: 'lane', bunny: 'bunny', urgency: 'Daddy', fork: 'fork', reveal: 'house', argument: 'voices', stay: 'stay', end: 'end' };

function row(label, beats, end, note) {
  const t = Object.fromEntries(beats.map((b) => [b.id, b.t]));
  const seq = ORDER.filter((k) => t[k] != null);
  const gaps = seq.slice(1).map((k, i) => ({ from: seq[i], to: k, s: +(t[k] - t[seq[i]]).toFixed(1) }));
  const longest = gaps.reduce((a, g) => (g.s > a.s ? g : a), { s: 0 });
  return {
    label, end: +end.toFixed(1), beats: Object.fromEntries(seq.map((k) => [k, t[k]])), note,
    gaps: seq.slice(1).map((k, i) => `${SHORT[seq[i]]}→${SHORT[k]} ${gaps[i].s}`).join(' · ') + ` (longest: ${SHORT[longest.from]}→${SHORT[longest.to]} ${longest.s} s)`,
  };
}

const out = { when: new Date().toISOString(), runs: [] };
const res = path.join(ROOT, 'playtest-output', 'results.json');
if (fs.existsSync(res)) {
  const r = JSON.parse(fs.readFileSync(res, 'utf8'));
  out.playtest = { when: r.when, passed: r.passed, failed: r.failed };
  // one row per check: name, a short readable result, and a hub status (failed checks show as unverified)
  const brief = (x) => Object.entries(x).filter(([k]) => !['name', 'pass'].includes(k)).map(([k, v]) => `${k}: ${typeof v === 'object' ? JSON.stringify(v) : v}`).join('; ').slice(0, 180);
  out.checks = r.results.map((x) => [x.name, (x.pass ? '' : 'FAILED. ') + brief(x), x.pass ? 'agent-tested' : 'unverified']);
  const R = r.runs || {};
  if (R.full) out.runs.push(row('Agent · desktop', R.full.beats, R.full.endTime, `npm run playtest: desktop keyboard, straight steering between waypoints; E at the gate twice and at the bunny; the ${R.full.beats.find((b) => b.id === 'fork')?.way || '?'} way.`));
}
for (const dir of walks) {
  const f = path.join(ROOT, dir, 'walk.json'); if (!fs.existsSync(f)) continue;
  const w = JSON.parse(fs.readFileSync(f, 'utf8'));
  const beats = w.beats.map((x) => { const [id, t] = x.split('@'); return { id, t: +t }; });
  const way = /firm/.test(dir) ? 'firm' : 'mud';
  out.runs.push(row(`Agent · phone, ${way}`, beats, w.endTime, `tools/walkthrough.mjs: emulated 390×844 phone, keyboard input, the ${way} way at the fork.`));
}
fs.writeFileSync(path.join(ROOT, 'hub', 'timings.js'), '// Generated by tools/hub-timings.mjs. Do not edit by hand.\nwindow.HUB_TIMINGS = ' + JSON.stringify(out, null, 1) + ';\n');
console.log(`hub/timings.js: ${out.runs.length} runs`, out.runs.map((r) => `${r.label} ${r.end}s`).join(', '));
