// Writes hub/timings.js from the latest automated runs, so the hub's "Observed timing" stays current:
// the full play-throughs in playtest-output/results.json (mud, sidewalk, fast) and the phone
// play-through recorded by tools/capture.mjs (hub/media/<set>/capture.json).
//
// Usage: node tools/hub-timings.mjs [--set=opening-v2]      (run after `npm run playtest` and a capture)
import fs from 'node:fs';
import path from 'node:path';

const ROOT = path.resolve(import.meta.dirname, '..');
const set = (process.argv.find((a) => a.startsWith('--set=')) || '--set=opening-v3').slice(6);
const ORDER = ['search', 'call2', 'creak', 'park', 'prints', 'lane', 'bunny', 'urgency', 'locked', 'over', 'reveal', 'argument', 'stay', 'end'];
const SHORT = { search: 'start', call2: 'call', creak: 'creak', park: 'park', prints: 'prints', lane: 'lane', bunny: 'bunny', urgency: 'Daddy', locked: 'locked', over: 'over', reveal: 'house', argument: 'voices', stay: 'stay', end: 'end' };

function row(label, beats, end, note) {
  const t = Object.fromEntries(beats.map((b) => [b.id, b.t]));
  const seq = ORDER.filter((k) => t[k] != null);
  const gaps = seq.slice(1).map((k, i) => ({ from: seq[i], to: k, s: +(t[k] - t[seq[i]]).toFixed(1) }));
  const longest = gaps.reduce((a, g) => (g.s > a.s ? g : a), { s: 0 });
  return {
    label, end: +end.toFixed(1), beats: Object.fromEntries(seq.map((k) => [k, t[k]])), note,
    gaps: seq.slice(1).map((k, i) => `${SHORT[seq[i]]}→${SHORT[k]} ${gaps[i].s}`).join(' · ') + ` (longest: ${SHORT[longest.from]}→${SHORT[longest.to]} ${longest.s} s)`,
  };
}

const out = { when: new Date().toISOString(), runs: [] };
const res = path.join(ROOT, 'playtest-output', 'results.json');
if (fs.existsSync(res)) {
  const r = JSON.parse(fs.readFileSync(res, 'utf8'));
  out.playtest = { when: r.when, passed: r.passed, failed: r.failed };
  // one row per check: name, a short readable result, and a hub status (failed checks show as unverified)
  const brief = (x) => Object.entries(x).filter(([k]) => !['name', 'pass'].includes(k)).map(([k, v]) => `${k}: ${typeof v === 'object' ? JSON.stringify(v) : v}`).join('; ').slice(0, 180);
  out.checks = r.results.map((x) => [x.name, (x.pass ? '' : 'FAILED. ') + brief(x), x.pass ? 'agent-tested' : 'unverified']);
  const R = r.runs || {};
  if (R.full) out.runs.push(row('Agent · pass 2', R.full.beats, R.full.endTime, 'Desktop keyboard, steering straight between waypoints at Marc’s one walking pace; E at the bunny, E twice at the gate.'));
}
const cap = path.join(ROOT, 'hub', 'media', set, 'capture.json');
if (fs.existsSync(cap)) {
  const c = JSON.parse(fs.readFileSync(cap, 'utf8'));
  if (c.playthrough) out.runs.push(row('Agent · phone', c.playthrough.beats, c.playthrough.endTime, `Capture run (${set}, commit ${c.commit}): emulated 390×844 phone, keyboard input, mud route, recorded as three clips.`));
}
fs.writeFileSync(path.join(ROOT, 'hub', 'timings.js'), '// Generated by tools/hub-timings.mjs. Do not edit by hand.\nwindow.HUB_TIMINGS = ' + JSON.stringify(out, null, 1) + ';\n');
console.log(`hub/timings.js: ${out.runs.length} runs`, out.runs.map((r) => `${r.label} ${r.end}s`).join(', '));
