// Makes the game's runtime assets small enough for a phone.
//
//   textures: assets/source/polyhaven/textures/<id>/{diff,nor}.jpg (1k originals, gitignored, from
//             tools/fetch-polyhaven.mjs) -> public/assets/textures/<id>/{diff,nor}.webp
//             (color 1024 px q76, normal 512 px q85; roughness maps are not used)
//   foliage:  assets/source/foliage/*.png (generated by Blender) -> public/assets/textures/foliage/*.webp
//   models:   public/assets/models/kit/*.glb and marc.glb -> meshopt-compressed; embedded textures
//             (Poly Haven props, vehicles, Marc) resized and re-encoded as WebP
//
// Usage: node tools/optimize-assets.mjs [--textures] [--models]   (both by default)
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { execFileSync } from 'node:child_process';
import sharp from 'sharp';

const ROOT = path.resolve(import.meta.dirname, '..');
const args = process.argv.slice(2), all = !args.length;
const SRC = path.join(ROOT, 'assets/source/polyhaven/textures'), OUT = path.join(ROOT, 'public/assets/textures');
let before = 0, after = 0;

if (all || args.includes('--textures')) {
  // move any downloaded originals out of public into the source folder (once)
  for (const id of fs.readdirSync(OUT)) {
    if (id === 'foliage') continue;
    const d = path.join(OUT, id);
    for (const f of fs.readdirSync(d).filter((f) => f.endsWith('.jpg'))) {
      fs.mkdirSync(path.join(SRC, id), { recursive: true });
      fs.renameSync(path.join(d, f), path.join(SRC, id, f));
    }
  }
  for (const id of fs.readdirSync(SRC)) {
    fs.mkdirSync(path.join(OUT, id), { recursive: true });
    for (const [k, size, q] of [['diff', 1024, 76], ['nor', 512, 85]]) {
      const src = path.join(SRC, id, k + '.jpg'); if (!fs.existsSync(src)) continue;
      const dst = path.join(OUT, id, k + '.webp');
      await sharp(src).resize(size, size).webp({ quality: q }).toFile(dst);
      before += fs.statSync(src).size; after += fs.statSync(dst).size;
    }
  }
  const fol = path.join(OUT, 'foliage');
  for (const f of fs.readdirSync(fol).filter((f) => f.endsWith('.png'))) {
    const src = path.join(fol, f), dst = src.replace(/\.png$/, '.webp');
    await sharp(src).webp({ quality: 88, alphaQuality: 92 }).toFile(dst);
    before += fs.statSync(src).size; after += fs.statSync(dst).size;
  }
  console.log(`textures: ${(before / 1e6).toFixed(1)} MB -> ${(after / 1e6).toFixed(1)} MB`);
}

if (all || args.includes('--models')) {
  const cli = path.join(ROOT, 'node_modules/@gltf-transform/cli/bin/cli.js');
  const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'opt-'));
  let b = 0, a = 0;
  const files = [...fs.readdirSync(path.join(ROOT, 'public/assets/models/kit')).filter((f) => f.endsWith('.glb')).map((f) => path.join(ROOT, 'public/assets/models/kit', f)), path.join(ROOT, 'public/assets/models/marc.glb')];
  for (const src of files) {
    const buf = fs.readFileSync(src);
    if (buf.includes('EXT_meshopt_compression')) { b += buf.length; a += buf.length; continue; }
    const out = path.join(tmp, path.basename(src));
    const hasImages = buf.includes('"images"');
    const size = path.basename(src) === 'marc.glb' ? '2048' : '512';
    execFileSync(process.execPath, [cli, 'optimize', src, out, '--compress', 'meshopt', '--texture-compress', hasImages ? 'webp' : 'false', '--texture-size', size,
      '--simplify', 'false', '--instance', 'false', '--join', 'false', '--flatten', 'false', '--palette', 'false', '--prune', 'false'], { stdio: 'ignore' });
    b += buf.length; a += fs.statSync(out).size;
    fs.copyFileSync(out, src);
  }
  console.log(`models: ${(b / 1e6).toFixed(1)} MB -> ${(a / 1e6).toFixed(1)} MB`);
}
