// Generated by tools/hub-timings.mjs. Do not edit by hand.
window.HUB_TIMINGS = {
 "when": "2026-10-01T05:27:18.989Z",
 "runs": [
  {
   "label": "Agent · desktop",
   "end": 76.6,
   "beats": {
    "search": 0.6,
    "prints": 2.1,
    "call2": 10.6,
    "creak": 24.5,
    "locked": 31.4,
    "over": 37.7,
    "park": 38.3,
    "lane": 45.5,
    "bunny": 47.7,
    "urgency": 51.6,
    "fork": 52.8,
    "reveal": 60.4,
    "argument": 62.6,
    "stay": 69.6,
    "end": 75.2
   },
   "note": "npm run playtest: desktop keyboard, straight steering between waypoints; E at the gate twice and at the bunny; the mud way.",
   "gaps": "start→prints 1.5 · prints→call 8.5 · call→creak 13.9 · creak→locked 6.9 · locked→over 6.3 · over→park 0.6 · park→lane 7.2 · lane→bunny 2.2 · bunny→Daddy 3.9 · Daddy→fork 1.2 · fork→house 7.6 · house→voices 2.2 · voices→stay 7 · stay→end 5.6 (longest: call→creak 13.9 s)"
  },
  {
   "label": "Agent · phone, mud",
   "end": 75.2,
   "beats": {
    "search": 0.6,
    "prints": 2.4,
    "call2": 10.9,
    "creak": 25.1,
    "locked": 32.2,
    "over": 38.4,
    "park": 39.2,
    "lane": 46.4,
    "bunny": 48.6,
    "urgency": 52.4,
    "fork": 53.6,
    "reveal": 61.3,
    "argument": 63.5,
    "stay": 68,
    "end": 73.7
   },
   "note": "tools/walkthrough.mjs: emulated 390×844 phone, keyboard input, the mud way at the fork.",
   "gaps": "start→prints 1.8 · prints→call 8.5 · call→creak 14.2 · creak→locked 7.1 · locked→over 6.2 · over→park 0.8 · park→lane 7.2 · lane→bunny 2.2 · bunny→Daddy 3.8 · Daddy→fork 1.2 · fork→house 7.7 · house→voices 2.2 · voices→stay 4.5 · stay→end 5.7 (longest: call→creak 14.2 s)"
  },
  {
   "label": "Agent · phone, firm",
   "end": 74.7,
   "beats": {
    "search": 0.6,
    "prints": 2.3,
    "call2": 10.8,
    "creak": 24.4,
    "locked": 31.4,
    "over": 37.6,
    "park": 38.2,
    "lane": 45.4,
    "bunny": 47.6,
    "urgency": 51.4,
    "fork": 54.3,
    "reveal": 58.3,
    "argument": 60.5,
    "stay": 69,
    "end": 73.2
   },
   "note": "tools/walkthrough.mjs: emulated 390×844 phone, keyboard input, the firm way at the fork.",
   "gaps": "start→prints 1.7 · prints→call 8.5 · call→creak 13.6 · creak→locked 7 · locked→over 6.2 · over→park 0.6 · park→lane 7.2 · lane→bunny 2.2 · bunny→Daddy 3.8 · Daddy→fork 2.9 · fork→house 4 · house→voices 2.2 · voices→stay 8.5 · stay→end 4.2 (longest: call→creak 13.6 s)"
  }
 ],
 "playtest": {
  "when": "2026-10-01T05:27:18.693Z",
  "passed": 17,
  "failed": 0
 },
 "checks": [
  [
   "load-and-start-card",
   "loadWallMs: 1914; gameLoadMs: 1739",
   "agent-tested"
  ],
  [
   "audio-starts-on-start-click",
   "audio: running",
   "agent-tested"
  ],
  [
   "starts-in-the-neighborhood-mid-search",
   "subtitle: Marc: Arianna?; section: street; ground: grass",
   "agent-tested"
  ],
  [
   "camera-fixed-angle",
   "before: [0,14.736]; after: [0,14.736]",
   "agent-tested"
  ],
  [
   "methodical-walk-while-searching",
   "walkSpeed: 1.3; withShift: 1.3; clipNaturalSpeed: 1.25",
   "agent-tested"
  ],
  [
   "collisions-hold",
   "houseWallX: 1.42; fenceX: 3.58; carX: 2.02",
   "agent-tested"
  ],
  [
   "gate-locked-then-climb",
   "againstGateZ: -33.58; promptAfterTry: <kbd>E</kbd> Climb over; afterClimb: [1.03,-34.85]; y: 0",
   "agent-tested"
  ],
  [
   "backtrack-over-the-gate",
   "afterClimbBack: [1.03,-33.15]",
   "agent-tested"
  ],
  [
   "run-and-mud",
   "firmSpeed: 3.6; firmGround: concrete; mudSpeed: 1.15; mudGround: mud; runClipSpeed: 4.48",
   "agent-tested"
  ],
  [
   "swing-and-trees-still-move",
   "swingA: 0.096; swingB: -0.088; leafMaterials: 91; wind: true; ms: 615",
   "agent-tested"
  ],
  [
   "play-through-to-the-end",
   "failAt: null; endTime: 76.6; beats: search@0.6 prints@2.1 call2@10.6 creak@24.5 locked@31.4 over@37.7 park@38.3 lane@45.5 bunny@47.7 urgency@51.6 fork@52.8 reveal@60.4 argument@62.",
   "agent-tested"
  ],
  [
   "searching-walk-then-run",
   "maxSpeedWhileSearching: 1.22; maxSpeedAfterHerCall: 3.6; way: mud",
   "agent-tested"
  ],
  [
   "restart-resets",
   "pos: [0.8,-0.3]; beats: [\"search\"]; running: false",
   "agent-tested"
  ],
  [
   "muted-play-has-text",
   "muted: true; lines: 1",
   "agent-tested"
  ],
  [
   "performance-desktop",
   "fps: 53; worstFrameMs: 50.5; drawCalls: 345; tris: 244937; note: desktop GPU, headless Chromium",
   "agent-tested"
  ],
  [
   "no-console-errors",
   "errors: []",
   "agent-tested"
  ],
  [
   "touch-walk-and-interact",
   "moved: 2.89; eLitAtBunny: true; carrying: true; note: emulated 390x844, not a physical phone",
   "agent-tested"
  ]
 ]
};
