// Generated by tools/hub-timings.mjs. Do not edit by hand.
window.HUB_TIMINGS = {
 "when": "2026-10-01T03:51:41.145Z",
 "runs": [
  {
   "label": "Agent · pass 2",
   "end": 93.6,
   "beats": {
    "search": 0.6,
    "call2": 15,
    "creak": 24.4,
    "park": 32.7,
    "prints": 41.1,
    "lane": 56.5,
    "bunny": 64.3,
    "urgency": 68.2,
    "locked": 73.9,
    "over": 79.7,
    "reveal": 79.7,
    "argument": 82.3,
    "stay": 86.8,
    "end": 92.2
   },
   "note": "Desktop keyboard, steering straight between waypoints at Marc’s one walking pace; E at the bunny, E twice at the gate.",
   "gaps": "start→call 14.4 · call→creak 9.4 · creak→park 8.3 · park→prints 8.4 · prints→lane 15.4 · lane→bunny 7.8 · bunny→Daddy 3.9 · Daddy→locked 5.7 · locked→over 5.8 · over→house 0 · house→voices 2.6 · voices→stay 4.5 · stay→end 5.4 (longest: prints→lane 15.4 s)"
  }
 ],
 "playtest": {
  "when": "2026-10-01T03:50:20.892Z",
  "passed": 13,
  "failed": 0
 },
 "checks": [
  [
   "load-and-start-card",
   "loadWallMs: 2221; gameLoadMs: 2016",
   "agent-tested"
  ],
  [
   "audio-starts-on-start-click",
   "audio: running",
   "agent-tested"
  ],
  [
   "starts-on-the-seawall-mid-search",
   "subtitle: Marc: Arianna?; ground: concrete",
   "agent-tested"
  ],
  [
   "camera-fixed-angle",
   "before: [0,15.476]; after: [0,15.476]",
   "agent-tested"
  ],
  [
   "methodical-walk-no-run",
   "walkSpeed: 1.3; withShift: 1.3; clipNaturalSpeed: 1.25",
   "agent-tested"
  ],
  [
   "collisions-hold",
   "parapetX: -2.43; fenceX: 4.13",
   "agent-tested"
  ],
  [
   "gate-locked-then-climb",
   "againstGateZ: -69.78; promptAfterTry: <kbd>E</kbd> Climb over; afterClimb: [23.2,-71.05]; y: 0",
   "agent-tested"
  ],
  [
   "play-through-to-the-end",
   "failAt: null; endTime: 93.6; beats: search@0.6 call2@15 creak@24.4 park@32.7 prints@41.1 lane@56.5 bunny@64.3 urgency@68.2 locked@73.9 over@79.7 reveal@79.7 argument@82.3 stay@86.8",
   "agent-tested"
  ],
  [
   "restart-resets",
   "pos: [-0.6,9.5]; beats: [\"search\"]",
   "agent-tested"
  ],
  [
   "muted-play-has-text",
   "muted: true; lines: 1",
   "agent-tested"
  ],
  [
   "performance-desktop",
   "fps: 60; worstFrameMs: 58.7; drawCalls: 248; tris: 243380; note: desktop GPU, headless Chromium",
   "agent-tested"
  ],
  [
   "no-console-errors",
   "errors: []",
   "agent-tested"
  ],
  [
   "touch-walk-and-interact",
   "moved: 3.05; eLitAtBunny: true; carrying: true; note: emulated 390x844, not a physical phone",
   "agent-tested"
  ]
 ]
};
